### ISSUE TITLE
Metadata Editor Improvements

### ISSUE THREAD

**Issue by michael** [substance/texture#607]
Here's a bunch of tasks related to improving the Metadata Editor:

- [x] Display warnings as overlays when cursor is in input field (to avoid jumping and make interface more minimal)
- [x] Remove add buttons in the document (should go into toolbar)
- [x] Use box shadow for cards (like we do for tables, figures, etc in main content)
- [x] Make section headings look like regular headings
- [x] Use same font size in InPlaceEditor
- [x] MultiSelectInput: Display one option per line (better to scan); find a way to indicate this is an input field and clickable
- [x] Adding and removing of authors (InPlaceEditor) does not work
- [x] When authors are changed in InPlaceEditor card does not update (we should add some kind of hierarchical listener)
- [x] Placeholders (Enter Text...) should look visually distinctive: Maybe more grey and italic? (don't know how to style native placeholders of inputs)
- [x] Add missing labels (some labels are missing e.g. for "sponsors")
- [x] Editors for figures + tables + footnotes: editing currently does not work: Either fix everything including style etc. or disable these sections for demo
- [x] Improve CSS (less redundancy better modularity)
- [x] When item is removed from collection (counts in the TOC are not updated)
- [x] move code from InplaceEditor into RefContribEditor and call it sc-ref-contrib-editor

**Comment by michael** [comment]
Regarding improve CSS: _entity-editor.css is leaking a lot of styles (e.g. overriding hover for text inputs etc., this should go into the css of the individual component).

Also things like:

```css
.sc-entity-editor .sc-text-input label,
.sc-entity-editor .sc-in-place-editor label,
.sc-entity-editor .sc-select-input .se-label,
.sc-entity-editor .sc-checkbox .se-label,
.sc-entity-editor .sc-multi-select-input .se-label {
  display: block;
  flex: 1 0 200px;
  margin-bottom: 0px;
  color: var(--label-color);
  font-size: var(--label-font-size);
  font-weight: var(--label-font-weight);
  line-height: var(--label-line-height);
}
```

we should avoid, as it will not scale with adding more input types. The best thing would be to not include labels in the TextInput etc. component (as this is redundant stuff). It would be better to introduce a FormRowComponent (which will handle generic things such as the layout of label and editor widget.

In EntityEditor:

```js
$$(FormRow, {
  label: this.getLabel('fooadf'),
  warnings: ['Title missing'] // will display a warning sign next to the label
             // and will pass warning true and will add `sm-warning` class to the editor which will then know how to render the warning
}).append(
  $$(TextInput, {...})
)
```

This will solve the warning problem (pointed out above) elegantly. Like we let handle FormRow the warnings.
